version: '3.9'

services:

  movie-app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    tty: true
    hostname: movie
    container_name: movie
    # start the movie container once get the healthy signal from mysqldb container.
    depends_on:
      mysqldb:
        condition: service_healthy
    security_opt:
        - "seccomp:unconfined"
    ports:
        - "9000:9000"
  
  mysqldb:
    image: mysql:8.0
    user: root:root
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: 65333
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 65333:65333
    restart: unless-stopped
    # u can tweak the healthcheck parameters for faster loading of mysql and hence the app.
    # https://docs.docker.com/engine/reference/builder/#healthcheck
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 20s